#!/usr/bin/env bash
# Build the Maia 2 custom WASM runtime.
#
# Required env:
#   MASTER_PUBLIC_KEY_HEX  — same 64-char hex used to build Patricia. The
#                            license check is the same Ed25519 chain.
#
# Optional:
#   LICENSE_URL  — defaults to https://engine.chessr.io/api/license/verify
#   BUILD_TYPE   — release (default) | debug
#
# Inputs (must exist):
#   wasm/weights_data.cpp — auto-generated by extract_weights.py from blitz.onnx
#
# Outputs:
#   wasm/maia.{js,wasm}

set -euo pipefail
cd "$(dirname "$0")"

if [[ -z "${MASTER_PUBLIC_KEY_HEX:-}" ]]; then
  echo "ERROR: MASTER_PUBLIC_KEY_HEX not set." >&2
  exit 1
fi

if [[ ! "$MASTER_PUBLIC_KEY_HEX" =~ ^[0-9a-fA-F]{64}$ ]]; then
  echo "ERROR: MASTER_PUBLIC_KEY_HEX must be exactly 64 hex chars." >&2
  exit 1
fi

if [[ ! -f "weights_data.cpp" ]]; then
  echo "ERROR: weights_data.cpp not found. Run extract_weights.py first:" >&2
  echo "  python ../scripts/extract_weights.py --onnx ../../python/models/blitz_model.onnx --out weights_data.cpp" >&2
  exit 1
fi

PUBKEY_BODY=$(echo "$MASTER_PUBLIC_KEY_HEX" | fold -w2 | awk '{printf "0x%s, ", $0}' | sed 's/, $//')
TMP_LICENSE="$(pwd)/license.build.cpp"
trap 'rm -f "$TMP_LICENSE"' EXIT

awk -v pubkey="$PUBKEY_BODY" '
  /\/\*MASTER_PUBLIC_KEY_PLACEHOLDER\*\// {
    print "  " pubkey;
    skip = 1; next;
  }
  skip && /^[[:space:]]*0x00,/ { next; }
  skip && /^};/ { skip = 0; print; next; }
  skip { next; }
  { print; }
' ../../patricia-build/wasm/license.cpp > "$TMP_LICENSE"

LICENSE_URL="${LICENSE_URL:-https://engine.chessr.io/api/license/verify}"
BUILD_TYPE="${BUILD_TYPE:-release}"

EXTRA_DEFINES=""
if [[ "$BUILD_TYPE" == "debug" ]]; then
  OPT_FLAGS="-O0 -g"
elif [[ "$BUILD_TYPE" == "test" ]]; then
  OPT_FLAGS="-O3 -ffast-math -msimd128 -DLICENSE_TEST_MODE=1"
elif [[ "$BUILD_TYPE" == "verbose" ]]; then
  OPT_FLAGS="-O2 -msimd128"
  EXTRA_DEFINES="-DDISABLE_OBFS=1 -DLICENSE_DEBUG=1"
else
  OPT_FLAGS="-O3 -ffast-math -msimd128"
fi

ENV_TARGET="${ENV_TARGET:-worker}"
OUT_BASENAME="${OUT_BASENAME:-maia}"

echo "Building $OUT_BASENAME.{js,wasm}"
echo "  build_type   = $BUILD_TYPE"
echo "  env_target   = $ENV_TARGET"
echo "  license_url  = $LICENSE_URL"
echo "  pubkey (hex) = ${MASTER_PUBLIC_KEY_HEX:0:8}…${MASTER_PUBLIC_KEY_HEX: -8}"

em++ \
  maia_wasm.cpp \
  ../src/ops.cpp \
  ../src/model.cpp \
  ../src/encoding.cpp \
  weights_data.cpp \
  "$TMP_LICENSE" \
  ../../patricia-build/wasm/monocypher/monocypher.c \
  $OPT_FLAGS \
  $EXTRA_DEFINES \
  -std=c++20 -DNDEBUG \
  -I../src \
  -I../../patricia-build/wasm \
  -DLICENSE_URL_OVERRIDE="\"$LICENSE_URL\"" \
  -s WASM=1 -s MODULARIZE=1 -s EXPORT_ES6=0 \
  -s ENVIRONMENT=$ENV_TARGET \
  -s FETCH=1 \
  -s INITIAL_MEMORY=128MB -s ALLOW_MEMORY_GROWTH=1 \
  -s STACK_SIZE=8MB \
  -s NO_EXIT_RUNTIME=1 \
  -s EXPORTED_RUNTIME_METHODS='["cwrap","ccall","HEAPF32","HEAPU8","getValue","addRunDependency","removeRunDependency"]' \
  -s EXPORTED_FUNCTIONS='["_wasm_init","_wasm_set_auth_token","_wasm_predict","_wasm_logits_ptr","_wasm_logits_count","_wasm_value","_malloc","_free"]' \
  -o "$OUT_BASENAME.js"

echo "Built:"
ls -lh "$OUT_BASENAME.js" "$OUT_BASENAME.wasm"
