#!/usr/bin/env bash
# Build the Maia 2 custom WASM runtime.
#
# Optional env:
#   BUILD_TYPE   — "release" (default) or "debug"
#
# Inputs:
#   wasm/weights_data.cpp — auto-generated by extract_weights.py
#
# Outputs:
#   wasm/maia.{js,wasm}

set -euo pipefail
cd "$(dirname "$0")"

if [[ ! -f "weights_data.cpp" ]]; then
  echo "ERROR: weights_data.cpp not found. Run extract_weights.py first:" >&2
  echo "  python ../scripts/extract_weights.py --onnx ../../python/models/blitz_model.onnx --out weights_data.cpp" >&2
  exit 1
fi

BUILD_TYPE="${BUILD_TYPE:-release}"

if [[ "$BUILD_TYPE" == "debug" ]]; then
  OPT_FLAGS="-O0 -g"
else
  OPT_FLAGS="-O3 -ffast-math -msimd128"
fi

ENV_TARGET="${ENV_TARGET:-worker}"
OUT_BASENAME="${OUT_BASENAME:-maia}"

echo "Building $OUT_BASENAME.{js,wasm}"
echo "  build_type = $BUILD_TYPE"
echo "  env_target = $ENV_TARGET"

em++ \
  maia_wasm.cpp \
  ../src/ops.cpp \
  ../src/model.cpp \
  ../src/encoding.cpp \
  weights_data.cpp \
  $OPT_FLAGS \
  -std=c++20 -DNDEBUG \
  -I../src \
  -s WASM=1 -s MODULARIZE=1 -s EXPORT_ES6=0 \
  -s ENVIRONMENT=$ENV_TARGET \
  -s INITIAL_MEMORY=128MB -s ALLOW_MEMORY_GROWTH=1 \
  -s STACK_SIZE=8MB \
  -s NO_EXIT_RUNTIME=1 \
  -s EXPORTED_RUNTIME_METHODS='["cwrap","ccall","HEAPF32","HEAPU8","getValue","addRunDependency","removeRunDependency"]' \
  -s EXPORTED_FUNCTIONS='["_wasm_init","_wasm_predict","_wasm_logits_ptr","_wasm_logits_count","_wasm_value","_malloc","_free"]' \
  -o "$OUT_BASENAME.js"

echo "Built:"
ls -lh "$OUT_BASENAME.js" "$OUT_BASENAME.wasm"
