-- ─────────────────────────────────────────────────────────────────────────
-- Wheel-of-fortune economy: tokens → spin → rewards (in inventory) → claim/gift.
--
-- Two-table model:
--
--   wheel_tokens   1 per ticket-earning action (boost today; purchase /
--                  admin grant tomorrow). Spinnable by the owner only.
--                  spun_at flips when consumed; reward_id points at the
--                  resulting wheel_rewards row.
--
--   wheel_rewards  Generated by spinning a token. Sits in someone's
--                  inventory (owner_discord_id) until claimed (applied to
--                  chessr account) or gifted (changes owner_discord_id).
--
-- Generic by design: a token's `source` distinguishes how it was earned
-- so we can layer purchase / referral / event flows without renaming
-- tables. `external_ref` is the per-source idempotency key (e.g.
-- premium_since for boosts, paddle txn id for purchases).
-- ─────────────────────────────────────────────────────────────────────────

DROP TABLE IF EXISTS discord_boosts;
DROP TABLE IF EXISTS boost_rewards;
DROP TABLE IF EXISTS boost_tokens;
DROP TABLE IF EXISTS wheel_rewards;
DROP TABLE IF EXISTS wheel_tokens;

CREATE TABLE wheel_tokens (
  id               bigserial   PRIMARY KEY,
  -- Token belongs to whoever earned it. Tokens themselves aren't
  -- giftable — only the resulting rewards are. So owner is immutable.
  owner_discord_id text         NOT NULL,
  -- How the token was earned. Adding a new source = adding a new value
  -- here; keep the CHECK list tight to surface typos at insert time.
  source           text         NOT NULL CHECK (source IN ('boost','purchase','admin_grant')),
  -- Per-source idempotency key. Boosts use premium_since ISO; purchases
  -- use the paddle transaction id; admin grants leave it null.
  external_ref     text,
  earned_at        timestamptz  NOT NULL DEFAULT now(),
  spun_at          timestamptz,
  reward_id        bigint
);

-- Idempotency: a single (owner, source, external_ref) tuple records at
-- most one token. Partial index — sources without dedup (admin_grant)
-- bypass the constraint by passing NULL.
CREATE UNIQUE INDEX uniq_wheel_tokens_dedup
  ON wheel_tokens(owner_discord_id, source, external_ref)
  WHERE external_ref IS NOT NULL;

-- Hot path: /spin and /inventory both read "give me unspun tokens for
-- this owner ordered by earned_at".
CREATE INDEX idx_wheel_tokens_unspun
  ON wheel_tokens(owner_discord_id, earned_at)
  WHERE spun_at IS NULL;

CREATE TABLE wheel_rewards (
  id                     bigserial    PRIMARY KEY,
  -- Current holder — changes on gift. Inventory queries key off this.
  owner_discord_id       text          NOT NULL,
  -- Original spinner. Immutable: even after gifting, this stays so we
  -- can answer "who actually won this".
  spun_by_discord_id     text          NOT NULL,
  spun_at                timestamptz   NOT NULL DEFAULT now(),
  -- Best-effort link back to the consumed token. SET NULL on token
  -- delete so the audit row survives even if we ever clean up tokens.
  source_token_id        bigint        REFERENCES wheel_tokens(id) ON DELETE SET NULL,
  -- Prize: a finite number of days, or a one-shot lifetime grant.
  reward_kind            text          NOT NULL CHECK (reward_kind IN ('days','lifetime')),
  reward_days            integer,
  CHECK ((reward_kind = 'days'     AND reward_days > 0) OR
         (reward_kind = 'lifetime' AND reward_days IS NULL)),
  -- Last-hop gift trail. Multi-hop chain (A→B→C) is reconstructed from
  -- the events table (wheel_gift events keyed by reward id), not here.
  gifted_from_discord_id text,
  gifted_at              timestamptz,
  -- Claim state. Once stamped, the reward is locked.
  claimed_at             timestamptz,
  claimed_by_user_id     uuid,
  reward_path            text          CHECK (reward_path IN ('paddle','dashboard','lifetime_set'))
);

-- Hot path: /inventory reads unclaimed-rewards-for-owner.
CREATE INDEX idx_wheel_rewards_unclaimed
  ON wheel_rewards(owner_discord_id, spun_at DESC)
  WHERE claimed_at IS NULL;

-- Audit / activity feeds.
CREATE INDEX idx_wheel_rewards_claimed_at
  ON wheel_rewards(claimed_at DESC)
  WHERE claimed_at IS NOT NULL;
