#!/usr/bin/env python3
"""
Generate a C++ TU that exposes Patricia's three NNUE nets as
extern "C" const unsigned char arrays — a WASM-compatible replacement for
the .incbin assembly directives in nnue.h, which Emscripten's WASM backend
can't process.
"""

import sys
from pathlib import Path

NETS = [
    ("g_nnueData",  "../src/engine/nets/fingolfin.nnue"),
    ("g_nnue2Data", "../src/engine/nets/finarfin.nnue"),
    ("g_nnue3Data", "../src/engine/nets/feanor.nnue"),
]

ROOT = Path(__file__).parent.resolve()
out_path = ROOT / "nnue_data.cpp"

with open(out_path, "w") as out:
    out.write("// Auto-generated by embed_nnue.py — embeds Patricia NNUE nets\n")
    out.write("// for WASM (incbin replacement).\n\n")
    out.write('extern "C" {\n\n')

    for sym, src in NETS:
        data = (ROOT / src).read_bytes()
        n = len(data)
        # - `extern` overrides C++'s implicit internal linkage for const
        #   namespace-scope variables (linker needs external symbol).
        # - `alignas(64)` matches NNUE_Params' alignment; Patricia
        #   reinterpret_casts this pointer to a struct that holds SIMD-aligned
        #   int16 arrays. Without it → OOB reads in the vectorised eval.
        out.write(f"alignas(64) extern const unsigned char {sym}[{n}] = {{\n")
        for i in range(0, n, 16):
            chunk = data[i : i + 16]
            line = ", ".join(f"0x{b:02x}" for b in chunk)
            out.write(f"  {line},\n")
        out.write("};\n\n")

    out.write("} // extern \"C\"\n")

print(f"wrote {out_path} ({out_path.stat().st_size / 1e6:.1f} MB)")
